# Auto-generated by Chef (original on chef repo: chef-container/container_solo.rb)
#
# Important: we disable all but essential plugins for chef-solo on the container to
# speed up the chef run.
#
# If new cookbooks are created for the container one might have to enable a plugin but
# mind the performance! Prefer what is already enabled.

all_plugins = [:CloudV2, :Cloud, :VirtualizationInfo, :Virtualization, :CPU, :Memory, :Filesystem, :Network, :NetworkRoutes, :NetworkListeners, :NetworkAddresses, :Kernel, :OS, :LSB, :Platform, :Languages, :Ruby, :Nodejs, :Perl, :Lua, :Mono, :Erlang, :Python, :C, :PHP, :Groovy, :Java, :SystemProfile, :Uptime, :Chef, :Ohai, :EC2, :GCE, :Rackspace, :Eucalyptus, :Linode, :Openstack, :Azure, :InitPackage, :RootGroup, :Keys, :SSHHostKey, :DMI, :Hostname, :IpScopes, :OhaiTime, :Passwd, :Command, :PS, :BlockDevice, :Zpools]

enabled_plugins = [ :Platform, :Hostname, :OS, :Kernel, :Command, :PS]

Ohai::Config[:disabled_plugins] = all_plugins - enabled_plugins

cookbook_path '/var/chef-solo/cookbooks'
log_location  '/var/log/chef/solo.log'
ssl_verify_mode   :verify_peer
