name             "git_user"
maintainer       "ThoughtWorks, Inc."
maintainer_email "support@thoughtworks.com"
license          "MIT"
description      "Installs/Configures git_user"
version          "0.0.1"
